"""empty message

Revision ID: c242c7ccc36c
Revises: cf2336fbb4e1
Create Date: 2018-05-05 11:27:09.232692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c242c7ccc36c'
down_revision = 'cf2336fbb4e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_courses_timestamp'), 'courses', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_courses_timestamp'), table_name='courses')
    op.drop_column('courses', 'timestamp')
    # ### end Alembic commands ###
